name: Policy

on:
  push:
  pull_request:

jobs:

  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: docker://ghcr.io/example-policy-org/policy-checker:latest

